name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # run at the start of every day
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os.ver }} 
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.4', '8.10.2']
        cabal: ['3.0.0.0', '3.2.0.0']
        os:
          - ver: ubuntu-18.04
            libpci: libpci-352
          - ver: ubuntu-20.04
            libpci: libpci-364

    name: ${{ matrix.os.ver }} GHC ${{ matrix.ghc }} Cabal ${{ matrix.cabal }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        sudo apt-get install libpci-dev
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks --constraint="bindings-libpci ${{ matrix.os.libpci }}"
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks --constraint="bindings-libpci ${{ matrix.os.libpci }}" all
    - name: Run tests
      run: cabal test all
